# Generated by Django 3.0.8 on 2020-07-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='grand_total',
        ),
    ]
