# Generated by Django 3.0.8 on 2020-08-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
