# Generated by Django 3.0.8 on 2020-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0002_invoice_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
