# Generated by Django 3.0.8 on 2020-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0002_remove_invoice_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
