# Generated by Django 3.0.8 on 2020-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0003_auto_20200801_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
