# Generated by Django 3.0.8 on 2020-08-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invator', '0004_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Draft', 'Draft'), ('', '')], default='', max_length=9),
        ),
    ]
